apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpVENDQVMrZ0F3SUJBZ0lRR1lzV01SYnUrdFhMejVqbDJyRzl4VEFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTFNRE15TVRBek1UZ3dORm9YRFRNMU1ETXhPVEF6TVRndwpORm93RlRFVE1CRUdBMVVFQ2hNS2EzVmlaWEp1WlhSbGN6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VICkEwSUFCSVFjbFVKenVBZzFKVnRmQzRLcnJZRFdzWkIrSG0ycEpCbnFrdmJ2TjlYSW9EMHB6Zk5pYVY3bmxyY0UKZGJzOEkranNEbEthWVduZHpVUTJwV2ZENFd1allUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWRCZ05WSFNVRQpGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVVHZVlMb3c4R3F5K0RXRC9Mc1V1ak53L0hUdEF3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU1xcjVMelYKM0RYZTM5aEZYU2w5YzE2UFV3Uy9jblF6SU5VM1dxR2t0aFlMQWlBT2loT0t5bzRHdFJrSkh0YTlVV3hMYzNTeQpDOEI0UFl0V0dOZjRWNHNUeVE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://192.168.1.200:6443
  name: talos
contexts:
- context:
    cluster: talos
    namespace: default
    user: admin@talos
  name: admin@talos
current-context: admin@talos
kind: Config
preferences: {}
users:
- name: admin@talos
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJoVENDQVN1Z0F3SUJBZ0lSQUpEWklNVkdwL1hEdlcyeHUrTGR4VDR3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOVEF6TWpFd016UTNOVGhhRncweU5qQXpNakV3TXpRNApNRGhhTUNreEZ6QVZCZ05WQkFvVERuTjVjM1JsYlRwdFlYTjBaWEp6TVE0d0RBWURWUVFERXdWaFpHMXBiakJaCk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkpic0tZQXFzVXNTQlBTTmxmd0hkUmJnV0ozbXhXdmQKb0YwVllCUnBzZzNhMGxPMUwrZFlHN2tjRFBKaEc4RTVnZjBHalNHWXNudVZySFFRbnh3RUNscWpTREJHTUE0RwpBMVVkRHdFQi93UUVBd0lGb0RBVEJnTlZIU1VFRERBS0JnZ3JCZ0VGQlFjREFqQWZCZ05WSFNNRUdEQVdnQlFaCjVndWpEd2FyTDROWVA4dXhTNk0zRDhkTzBEQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUFrazd4S2NFeWNxUGQKYlFxRkV5RW5oTGl4VWtjV3dOMTVDbTdQaEZsblVSNENJQ3ZpcWpicEo1bGRaazhyQjBzTkJINTYzYi94RjFLSApMUXJzeENtekpVckcKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUl2V0x1OEZ4VW5ZWEVhOXNGa2tFZW5xc3g3WkNWMHRhcDdBeWovNmgwU1RvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFbHV3cGdDcXhTeElFOUkyVi9BZDFGdUJZbmViRmE5MmdYUlZnRkdteURkclNVN1V2NTFnYgp1UndNOG1FYndUbUIvUWFOSVppeWU1V3NkQkNmSEFRS1dnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
