apiVersion: v1
kind: PersistentVolume
metadata:
  name: authelia-nfs-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "" # <-- Explicitly set to empty string
  nfs:
    path: /mnt/Pool01_4TB_Mirror/Talos/authelia
    server: truenas
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-config-pvc
  namespace: authelia # <-- Must match Authelia's deployment namespace
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "" # <-- Tells K8s to look for your explicit PV
  resources:
    requests:
      storage: 1Gi
  volumeName: authelia-nfs-pv
  
