apiVersion: v1
kind: Service
metadata:
  name: homer-service
  namespace: default
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.1.230"
spec:
  type: LoadBalancer
  # --- ADD THIS LINE ---
  externalTrafficPolicy: Local
  # ----------------------
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: homer