apiVersion: v1
kind: PersistentVolume
metadata:
  name: actual-nfs-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/Pool01_4TB_Mirror/Talos/barassistant
    server: truenas
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-config-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: actual-nfs-pv