apiVersion: v1
kind: Service
metadata:
  name: barassistant-service
  namespace: default
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.1.232"
spec:
  type: LoadBalancer
  # --- ADD THIS LINE ---
  externalTrafficPolicy: Local
  # ----------------------
  ports:
    - port: 5006
      targetPort: 5006
      protocol: TCP
      name: http
  selector:
    app: barassistant